version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "deps"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      actions-major:
        patterns: ["*"]
        update-types: ["major"]